from __future__ import annotations

import re
from io import BytesIO
from typing import Iterable

import pandas as pd
from pptx import Presentation
from pptx.enum.shapes import PP_PLACEHOLDER

from aicf_config import (
    INSIGHT_CUES as _CONFIG_INSIGHT_CUES,
    NON_INSIGHT_CUES as _CONFIG_NON_INSIGHT_CUES,
    NON_INSIGHT_EXACT as _CONFIG_NON_INSIGHT_EXACT,
)

# v6: the cue lists used to contain vocabulary from specific past projects
# (a client name, a building-services word list). Those made slide selection
# behave differently depending on which study the deck came from. The shared,
# method-only lexicons now live in aicf_config.py.
INSIGHT_CUES = list(_CONFIG_INSIGHT_CUES)
# Substring cues only. Anything short enough to occur inside an ordinary
# sentence must go in EXCLUDE_EXACT instead, or it silently deletes insights.
EXCLUDE_CUES = list(_CONFIG_NON_INSIGHT_CUES) + [
    "paired/overlap", "capital letters", "significance difference",
]
EXCLUDE_EXACT = list(_CONFIG_NON_INSIGHT_EXACT)
ADMIN_TITLE_CUES = [
    "methodology", "target audience", "stimuli", "demographic", "profile overview",
    "appendix", "thank you", "follow up questions", "agenda", "contents",
]
TITLE_ONLY_CUES = [
    "executive summary", "key takeaway", "key takeaways", "net promoter score",
    "overall satisfaction", "brand perception", "unmet demand", "loyalty",
    "advocacy", "methodology", "sample",
]



def clean_text(value: object) -> str:
    text = " ".join(str(value or "").replace("\n", " ").split()).strip()
    if text.lower() in {"nan", "none", "null"}:
        return ""
    return text


def is_disclaimer(text: str) -> bool:
    lowered = text.lower()
    return (
        "this report was generated by displayr ai" in lowered
        or "ai can make mistakes" in lowered
        or lowered in {"background"}
    )


def placeholder_type(shape):
    try:
        return shape.placeholder_format.type
    except Exception:
        return None


def iter_shape_text(shape) -> Iterable[str]:
    if hasattr(shape, "text") and clean_text(shape.text):
        text = clean_text(shape.text)
        if not is_disclaimer(text):
            yield text

    if getattr(shape, "has_table", False):
        for row in shape.table.rows:
            cells = [clean_text(cell.text) for cell in row.cells if clean_text(cell.text)]
            if cells:
                yield " | ".join(cells)

    if getattr(shape, "has_chart", False):
        chart = shape.chart
        if chart.has_title:
            title = clean_text(chart.chart_title.text_frame.text)
            if title:
                yield title
        for series in chart.series:
            name = clean_text(getattr(series, "name", ""))
            if name:
                yield f"Chart series: {name}"

    if getattr(shape, "shape_type", None) == 6:
        for grouped_shape in shape.shapes:
            yield from iter_shape_text(grouped_shape)


def looks_like_admin_title(title: str, body: str = "") -> bool:
    combined = f"{title} {body}".lower().strip()
    if not combined:
        return True
    if combined in {"appendix", "thank you"}:
        return True
    return any(cue in combined for cue in ADMIN_TITLE_CUES)


def looks_like_question_or_note(text: str) -> bool:
    lowered = text.lower().strip()
    if not lowered or lowered in EXCLUDE_EXACT:
        return True
    if any(cue in lowered for cue in EXCLUDE_CUES):
        return True
    if re.match(r"^[a-z]*\d+[a-z._ &-]*[:.-]", lowered):
        return True
    if re.match(r"^[a-z]*\d+[a-z0-9._ &-]*:", lowered):
        return True
    if lowered.startswith(("q", "c", "a", "d")) and "?" in lowered and len(lowered.split()) > 8:
        return True
    return False


def looks_like_slide_heading(text: str) -> bool:
    cleaned = clean_text(text)
    lowered = cleaned.lower()
    words = len(re.findall(r"\w+", cleaned))
    if not cleaned:
        return True
    if any(cue in lowered for cue in TITLE_ONLY_CUES):
        return True
    if "theme in the study" in lowered or "key kpis" in lowered:
        return True
    if "theme" in lowered and words <= 12 and not has_numeric_or_evidence(cleaned):
        return True
    if cleaned.isupper() and words <= 9:
        return True
    if words <= 6 and not has_numeric_or_evidence(cleaned) and not any(
        cue in lowered
        for cue in [
            "because", "therefore", "suggest", "indicate", "drives", "needs work",
            "priority", "improve", "opportunity", "outlier", "gap", "lags",
            "highest", "lowest", "strongest", "weakest",
        ]
    ):
        return True
    return False


def has_numeric_or_evidence(text: str) -> bool:
    return bool(re.search(r"\b(n|base)\s*=\s*\d+|\d+(\.\d+)?\s*%|\d+(\.\d+)?\s*/\s*\d+|mean|top box|top-2", text, re.I))


def is_good_insight_candidate(text: str, title: str = "") -> bool:
    cleaned = clean_text(text)
    lowered = cleaned.lower()
    if cleaned == clean_text(title) or looks_like_question_or_note(cleaned) or looks_like_slide_heading(cleaned):
        return False
    words = len(re.findall(r"\w+", cleaned))
    if words < 5 or words > 90:
        return False
    return any(cue in lowered for cue in INSIGHT_CUES)


def is_fallback_insight_candidate(text: str, title: str = "") -> bool:
    cleaned = clean_text(text)
    lowered = cleaned.lower()
    if cleaned == clean_text(title) or looks_like_question_or_note(cleaned) or looks_like_slide_heading(cleaned):
        return False
    if "|" in cleaned:
        return False
    words = len(re.findall(r"\w+", cleaned))
    if words < 6 or words > 70:
        return False
    if re.fullmatch(r"[\d\s%.,|/-]+", cleaned):
        return False
    if lowered in {"net promoter score", "overall satisfaction", "what tenants want to see more of"}:
        return False
    if sum(ch.isdigit() for ch in cleaned) > max(8, len(cleaned) * 0.35):
        return False
    return True


def text_after_label(texts: list[str], label: str) -> str:
    label_lower = label.lower()
    for idx, text in enumerate(texts):
        if text.lower() == label_lower and idx + 1 < len(texts):
            return clean_text(texts[idx + 1])
    return ""


def text_before_label(texts: list[str], label: str) -> str:
    label_lower = label.lower()
    for idx, text in enumerate(texts):
        if text.lower() == label_lower and idx > 0:
            return clean_text(texts[idx - 1])
    return ""


def derived_insight_from_slide(title: str, texts: list[str]) -> str:
    combined = " ".join(texts).lower()
    if "nps" in combined and "promoters" in combined and "detractors" in combined:
        nps_value = text_before_label(texts, "NPS")
        promoters = text_after_label(texts, "Promoters (9–10)") or text_after_label(texts, "Promoters (9-10)")
        detractors = text_after_label(texts, "Detractors (0–6)") or text_after_label(texts, "Detractors (0-6)")
        details = []
        if nps_value:
            details.append(f"NPS {nps_value}")
        if promoters:
            details.append(f"{promoters} promoters")
        if detractors:
            details.append(f"{detractors} detractors")
        if details:
            return f"DLF Offices shows positive advocacy, with {', '.join(details)}."
    return ""


def trim_sentence(text: str, max_words: int = 42) -> str:
    cleaned = clean_text(text).replace("e.g.", "for example")
    parts = re.split(r"(?<=[.!?])\s+", cleaned)
    if parts and 8 <= len(parts[0].split()) <= max_words:
        return parts[0].strip()
    words = cleaned.split()
    if len(words) > max_words:
        return " ".join(words[:max_words]).rstrip(" ,;") + "."
    return cleaned


def evidence_from_texts(slide_index: int, title: str, texts: list[str]) -> str:
    evidence_bits = []
    for text in texts:
        lowered = text.lower()
        if looks_like_question_or_note(text) and not re.search(r"\b(n|base)\s*=\s*\d+|\d+%|95%|90%|top box|mean", text, re.I):
            continue
        if re.search(r"\b(n|base)\s*=\s*\d+|\d+%|95%|90%|top box|mean|purchase intent|fitment|appeal|recall|ecr|survey kpis", lowered, re.I):
            bit = trim_sentence(text, 34)
            if bit and bit not in evidence_bits:
                evidence_bits.append(bit)
        if len(evidence_bits) >= 2:
            break
    if evidence_bits:
        support = " ".join(evidence_bits)
        return f"PowerPoint report evidence from slide {slide_index} ({title}): {support}. Verify chart values against source tables before final client use."
    return f"PowerPoint report evidence from slide {slide_index} ({title}): insight is supported by the slide narrative/chart context. Verify chart values against source tables before final client use."


def read_pptx_insights(uploaded_file) -> pd.DataFrame:
    uploaded_file.seek(0)
    prs = Presentation(BytesIO(uploaded_file.read()))
    rows = []

    for slide_index, slide in enumerate(prs.slides, start=1):
        title = ""
        texts = []
        for shape in slide.shapes:
            text = clean_text(getattr(shape, "text", ""))
            if placeholder_type(shape) == PP_PLACEHOLDER.TITLE and text and not is_disclaimer(text):
                title = text
            for item in iter_shape_text(shape):
                if item and item not in texts:
                    texts.append(item)

        if (not title or "|" in title or looks_like_question_or_note(title)) and texts:
            title_candidates = [
                item for item in texts
                if "|" not in item
                and 2 <= len(item.split()) <= 16
                and not looks_like_question_or_note(item)
                and not is_good_insight_candidate(item, "")
            ]
            title = title_candidates[0] if title_candidates else texts[0]

        body_for_admin_check = " ".join(texts[:6])
        candidates = [text for text in texts if is_good_insight_candidate(text, title)]
        if looks_like_admin_title(title, body_for_admin_check):
            continue
        if slide_index == 1 and not candidates:
            continue
        if not candidates:
            candidates = [text for text in texts if is_fallback_insight_candidate(text, title)]
        if not candidates:
            derived = derived_insight_from_slide(title, texts)
            if derived:
                candidates = [derived]
        if not candidates:
            continue

        # Keep the strongest business-readable claim per slide. Prefer narrative sentences over raw tables.
        strong_verbs = [
            "outperforms", "drives", "shows", "reinforces", "anchors", "leads",
            "validates", "emerges", "delivers", "reframes", "suggests", "indicates",
            "satisfied", "lags", "trail", "needs work", "room for improvement",
            "area of improvement", "friction", "priority", "strong", "weak",
            "standout", "near-universal", "address", "gap", "gaps", "upgrade",
        ]
        def candidate_rank(candidate: str) -> tuple[int, int, int]:
            lowered = candidate.lower()
            pipe_penalty = 3 if "|" in candidate else 0
            note_penalty = 5 if "note :" in lowered else 0
            verb_bonus = -3 if any(verb in lowered for verb in strong_verbs) else 0
            prime_bonus = -1 if "prime" in lowered else 0
            length_penalty = abs(len(candidate.split()) - 24) // 12
            return (pipe_penalty + note_penalty + verb_bonus + prime_bonus + length_penalty, len(candidate.split()), len(candidate))
        candidates = sorted(candidates, key=candidate_rank)
        insight = trim_sentence(candidates[0])
        if not insight or insight.lower() == title.lower():
            continue

        rows.append(
            {
                "insight_id": f"PPT-S{slide_index:02d}",
                "theme": trim_sentence(title, 12)[:90] or "PowerPoint insight",
                "insight_text": insight,
                "evidence_note": evidence_from_texts(slide_index, title, texts),
            }
        )

    return pd.DataFrame(rows)
